[tool.ruff]
line-length = 89
src = ["src", "scripts", "optim"]
extend-exclude = ["data", "examples"]
target-version = "py311"

[tool.ruff.lint]
select = [
    "E", # pycodestyle error
    "W", # pycodestyle warnings
    "F", # Pyflakes
    "B", # flake8-bugbear
    "D", # pydocstyle
    "N", # pep8-naming
]
ignore = [
    "I001", # Imports are sorted by isort
    "E501",
    "B023",
    "D200",
]
unfixable = ["B"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "single"

[tool.isort]
length_sort = true
multi_line_output = 2  # Hanging indent
atomic = true
line_length = 79
